import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { ArrowLeft, BriefcaseBusiness, GraduationCap, MapPin, Star, UserRound } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Candidate = { id: string; full_name: string; headline: string | null; bio: string | null; city: string | null; state: string | null; is_pcd: boolean | null }

export function CandidateDetailsPage() {
  const [params] = useSearchParams(); const id = params.get('id')
  const [candidate, setCandidate] = useState<Candidate | null>(null); const [experiences, setExperiences] = useState<Array<{ id: string; title: string; company: string; current: boolean }>>([]); const [educations, setEducations] = useState<Array<{ id: string; course: string; institution: string; current: boolean }>>([]); const [message, setMessage] = useState('')
  useEffect(() => { void (async () => { if (!id) { setMessage('Selecione um candidato.'); return }; const [profile, experienceData, educationData] = await Promise.all([supabase.from('public_profiles').select('id, full_name, headline, bio, city, state, is_pcd').eq('id', id).single(), supabase.from('experiences').select('id, title, company, current').eq('candidate_id', id).order('started_on', { ascending: false }), supabase.from('educations').select('id, course, institution, current').eq('candidate_id', id)]); if (profile.error) setMessage('Não foi possível carregar o perfil do candidato.'); else setCandidate(profile.data); setExperiences(experienceData.data ?? []); setEducations(educationData.data ?? []) })() }, [id])
  if (message && !candidate) return <section className="workspace-card error-box"><UserRound size={22} /><div><h2>Candidato indisponível</h2><p>{message}</p></div></section>
  if (!candidate) return <section className="workspace-card loading-card"><div className="loading-dot" /><span>Carregando candidato...</span></section>
  const location = [candidate.city, candidate.state].filter(Boolean).join(', ') || 'Local não informado'
  return <section className="opportunity-flow"><Link className="flow-back" to="/contratante/candidates"><ArrowLeft size={16} /> Voltar para candidatos</Link><article className="workspace-card candidate-detail"><div className="candidate-heading"><span className="record-avatar"><UserRound size={22} /></span><div><span className="section-eyebrow">CANDIDATO</span><h2>{candidate.full_name}</h2><p>{candidate.headline || 'Profissional HOUK'}</p></div></div><div className="opportunity-meta"><span><MapPin size={16} />{location}</span>{candidate.is_pcd && <span>Perfil PCD</span>}</div>{candidate.bio && <section><h3>Sobre</h3><p>{candidate.bio}</p></section>}<div className="candidate-history"><section><h3><BriefcaseBusiness size={17} /> Experiência</h3>{experiences.length ? experiences.map(item => <p key={item.id}><strong>{item.title}</strong><br />{item.company}{item.current ? ' · Atual' : ''}</p>) : <p>Nenhuma experiência cadastrada.</p>}</section><section><h3><GraduationCap size={17} /> Formação</h3>{educations.length ? educations.map(item => <p key={item.id}><strong>{item.course}</strong><br />{item.institution}{item.current ? ' · Em curso' : ''}</p>) : <p>Nenhuma formação cadastrada.</p>}</section></div></article></section>
}

export function ReviewsPage({ role }: { role: 'candidate' | 'contractor' | 'admin' }) {
  const [items, setItems] = useState<Array<{ id: string; rating: number; comment: string | null; created_at: string }>>([]); const [message, setMessage] = useState('')
  useEffect(() => { void (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user && role !== 'admin') { setMessage('Faça login para consultar avaliações.'); return }; const query = role === 'admin' ? supabase.from('reviews').select('id, rating, comment, created_at').order('created_at', { ascending: false }) : supabase.from('reviews').select('id, rating, comment, created_at').eq('author_id', auth.user!.id).order('created_at', { ascending: false }); const { data, error } = await query; if (error) setMessage(`Não foi possível carregar avaliações: ${error.message}`); else setItems(data ?? []) })() }, [role])
  return <section className="workspace-card editor-card"><span className="section-eyebrow">AVALIAÇÕES</span><h2>{role === 'admin' ? 'Avaliações da plataforma' : 'Minhas avaliações'}</h2><p>Consulte os feedbacks que você publicou na HOUK.</p>{message && <p className="form-message">{message}</p>}{items.length ? <div className="reviews-list">{items.map(item => <article key={item.id}><strong><Star size={16} fill="currentColor" /> {item.rating}/5</strong><p>{item.comment || 'Sem comentário.'}</p></article>)}</div> : !message && <div className="empty-page compact"><Star size={28} /><h3>Nenhuma avaliação</h3><p>As avaliações publicadas aparecerão aqui.</p></div>}</section>
}
